#services:
#  postgres:
#    image: postgres:17.5
#    container_name: saas-db
#    environment:
#      POSTGRES_DB: ${DB_NAME:-saas-db}
#      POSTGRES_USER: ${DB_USER:-postgres}
#      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
#      PGDATA: /var/lib/postgresql/data/data
#    ports:
#      - "${DB_PORT:-5432}:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/data
#    networks:
#      - saas-app-network
#    restart: unless-stopped
#
#
#volumes:
#  postgres_data:
#    driver: local
#
#networks:
#  saas-app-network:
#    driver: bridge
services:

  postgres:
    image: postgres:17.5
    container_name: saas-postgres
    environment:
      POSTGRES_DB: saas-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: saas-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: saas-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: saas-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_PRIVATE_KEY_PATH: certs/private_key.pem
      JWT_PUBLIC_KEY_PATH: certs/public_key.pem
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
    driver: local